### ISSUE TITLE
Retos

### ISSUE THREAD

**Issue by jevillanueva** [javiermelom/psg-example#1]
Sigue adelante con los retos!! 

Vas muy bien.... :D
 
Por si no los encuentras aqui estan los retos de las otra sesiones:

- Sesión 2: https://study.pylapaz.org/content/sesion02/#/63
- Sesion 3: https://study.pylapaz.org/content/sesion03/#/84
- Sesión 4: https://study.pylapaz.org/content/sesion04/#/60

**Comment by javiermelom** [comment]
Hola *Jonathan*, ya me puse al día con los retos, me gustaría que los pudieras ver y si tienes sugerencias son bien recibidas siempre. Gracias.
