### ISSUE TITLE
Retos Python Study Group 

### ISSUE THREAD

**Issue by jevillanueva** [javiermelom/psg-example#2]
Hola!

Veo que aun faltan retos del python study group....  
Me gustaria invitarte a que continues 😄 
Aquí encontrarás todas las sesiones y sus retos  https://study.pylapaz.org/
No te desanimes!! estare atento a tus retos, animo!!! 

--- 
Feedback:

8.3. al crear tuplas de 1 solo elemento necesita de la coma ('!',) sin la coma no es una tupla sino una cadena 
10.3. falta codigo python
10.4 y 10.5 faltan un ejercicio y el notebook

Estas haciendo un gran trabajo tienes buen manejo de lógica y uso del ingles para las variables por legibilidad

Ya esta disponible los retos hasta la sesión 11 y tienes tiempo

Sigue adelante gran trabajo!!

> Hazlo simple, pero significativo. - Don Draper

**Comment by javiermelom** [comment]
Profe ya están arriba todos los ejercicios propuestos
